services:
  api:
    container_name: "authorization-service"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_ACTOR: ${GITHUB_ACTOR}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    ports:
      - 8000:8080
    environment:
      AUTH_SERVER_URI: https://dev-2dc74voarsscuyp0.us.auth0.com/

      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: ${AUTH_SERVER_URI}

      AUTH_CLIENT_ID: ${AUTH_CLIENT_ID}
      AUTH_AUDIENCE: ${AUTH_AUDIENCE}
      AUTH0_DOMAIN: ${dev-2dc74voarsscuyp0.us.auth0.com}
      AUTH0_MANAGEMENT_CLIENT_ID: ${AUTH_CLIENT_ID}
      AUTH0_MANAGEMENT_CLIENT_SECRET: ${AUTH_CLIENT_SECRET}

      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: authorization-serviceDB
      DB_HOST: postgres_db
      DB_PORT: 5432

      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      NEW_RELIC_APP_NAME: Snippet Searcher

    depends_on:
      - postgres_db

    networks:
      - printscript-net

  postgres_db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - printscript-net


networks:
  printscript-net:
    external: true
