services:
  api:
    container_name: "authorization-service"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_ACTOR: ${GITHUB_ACTOR}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    ports:
      - 8000:8080
    environment:
      AUTH_SERVER_URI: https://dev-2dc74voarsscuyp0.us.auth0.com/

      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: ${AUTH_SERVER_URI}

      AUTH_CLIENT_ID: ${AUTH_CLIENT_ID}
      AUTH_AUDIENCE: ${AUTH_AUDIENCE}

      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: authorization-serviceDB
      DB_HOST: postgres_db
      DB_PORT: 5432

      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      NEW_RELIC_APP_NAME: Snippet Searcher

    networks:
      - printscript-net

networks:
  printscript-net:
    name: printscript-net
